### ISSUE TITLE
Average FPS always 2% below wanted FPS

### ISSUE THREAD

**Issue by binarykitchen** [hapticdata/animitter#4]
Some initial tests have shown that whenever you specify a wanted FPS like 15 under options and then calculate your own average FPS in the loop, then it's about 2% below the wanted FPS in most times.

**Comment by hapticdata** [comment]
I am not seeing this issue on my side. Are you able to provide a small test showing this issue?

There are [tests for this](https://github.com/hapticdata/animitter/blob/master/test.js#L320-L358) but I admit there is some flex in this because throttling can only be as precise as `requestAnimationFrame` is. The logic is essentially _emit update if this tick is closer to your target than the next one is likely to be_ [see here](https://github.com/hapticdata/animitter/blob/master/index.js#L34).


I added this basic code to a project and it always reported 4 or 5 fps and never varied more than 2 milliseconds in the delta. Same behavior at other fps.

```js
const throttledLoop = animitter({ fps: 5 });
const fpsEl = document.createElement('div');
Object.assign(fpsEl.style, {
    position: 'fixed',
    top: '20px',
    left: '20px',
    zIndex: 100,
    color: 'white'
});

document.body.appendChild(fpsEl);
throttledLoop.on('update', function(delta){
    fpsEl.innerText = Math.round(1000/delta) + ' - ' + delta;
});
throttledLoop.start();
```

**Comment by hapticdata** [comment]
closing this since there hasnt been any traction on it, all tests I have done have reported within 1 or 2 milliseconds of the requested frame rate.

reopen if you can provide some test / example of the issue
